dist: xenial
sudo: false
latex: true
language: r
r: release

warnings_are_errors: false

cache:
  packages: true
  
apt_packages:
  - libgdal-dev
  - libudunits2-dev

r_packages:
  - rsconnect
  - shiny
  - tidyverse
  - kableExtra
  - e1071
  - data.table
  - ggplot2
  
script:
  - R -f deploy.R

notifications:
  email:
   - mikewalter@hotmail.fr
   
  email:
    recipients:
     - mikewalter@hotmail.fr
    on_success: <always|never|change>  # default: change
    on_failure: <always|never|change>  # default: always
